//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace URLShortnerDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TEST_DBEntities : DbContext
    {
        public TEST_DBEntities()
            : base("name=TEST_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<URL_DATA> URL_DATA { get; set; }
        public DbSet<USER_DATA> USER_DATA { get; set; }
        public DbSet<USER_URL_RECORDS> USER_URL_RECORDS { get; set; }
    }
}
