//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace URLShortnerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_DATA
    {
        public USER_DATA()
        {
            this.USER_URL_RECORDS = new HashSet<USER_URL_RECORDS>();
        }
    
        public int USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public string USER_IP_ADRESS { get; set; }
        public string USER_LOCATION { get; set; }
    
        public virtual ICollection<USER_URL_RECORDS> USER_URL_RECORDS { get; set; }
    }
}
