//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace URLShortnerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_URL_RECORDS
    {
        public int RECORD_ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public Nullable<int> URL_ID { get; set; }
    
        public virtual URL_DATA URL_DATA { get; set; }
        public virtual USER_DATA USER_DATA { get; set; }
    }
}
